dist: xenial
language: java

jdk: openjdk11

branches:
  only:
    - master

install:
  - chmod +x gradlew
  - ./gradlew wrapper

script: ./gradlew build jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - .autoconf
  - $HOME/.gradle
