version: 2.1

jobs:
  build:

    working_directory: ~/algorithm-playground

    docker:
      - image: circleci/openjdk:11.0.1-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          keys:
            - ap-dependencies-{{ checksum "build.gradle" }}
            - ap-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: ap-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew --version
      - run: ./gradlew test