version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:

    working_directory: ~/algorithm-playground

    docker:
      - image: circleci/openjdk:11.0.1-jdk-browsers

    steps:

      - checkout

      - restore_cache: # restore the saved cache after the first run or if `build.gradle` has changed
          key: algorithm-playground-{{ checksum "build.gradle" }}

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: algorithm-playground-{{ checksum "build.gradle" }}

      - run: ./gradlew --version
      - run: ./gradlew --scan --stacktrace build

      # Save test results
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - codecov/upload:
          file: {{ coverage_report_filepath }}